<a href="https://colab.research.google.com/github/datadigger01/Datahandling/blob/main/Code_example/week03_missingvalue_datanormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
[3주차] Missing Data & data normalization
"""
import numpy as np
import pandas as pd

In [ ]:
df_data=pd.read_csv('/content/drive/MyDrive/데이터처리실무/Data/Accident_Disability_Train_all.csv')
df_data

,UNIQUE_NO,NH_TARGET,TOT_HSPZ_DYS,SM_DSAS_ACNT_YR1,PSG_DYS_CNTR_RIST_ACDDY,TOT_ISAMT,HSPZ_CNT_YR1,BILG_ISAMT,SCRT_CNTR_CNT_MT3,CNTR_CNT_YR1,...,SARG_NPCNT_YR1,SARG_INPCNT_YR1,SARG_ACCNT_CMPR_NPCNT_RT_YR1,SAJG_ACCNT_YR1,SAJG_IVCNT_YR1,SAJG_NPCNT_YR1,SAJG_INPCNT_YR1,HSCLP_ACNT_YR1,ACNT_CLPHS_CTZ_DG_YR1,ACNT_HSCLP_CTZ_DG_YR1
0,1,1,0,0,7163,6000000,0,5000000,0,1,...,311,94,21.35989,6421,360,640,123,0,0.00000,0.00000
1,2,1,1,0,21,2750000,2,2500000,0,1,...,405,91,20.18943,0,0,0,0,0,0.00000,0.00000
2,3,1,6,0,143,29272880,2,27000000,0,1,...,712,229,17.04981,0,0,0,0,3,1.84049,0.26178
3,4,1,0,9,66,2750000,4,2500000,0,1,...,628,175,18.41102,0,0,0,0,11,1.47651,0.72464
4,5,1,0,6,215,28500000,0,27000000,0,1,...,503,71,17.06242,0,0,0,0,0,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1001,0,0,1,121,60000000,1,48000000,0,1,...,630,100,17.12887,0,0,0,0,2,2.08333,0.08989
1001,1002,0,0,2,3737,1500000,2,1000000,0,0,...,975,74,9.29545,1500,21,115,7,0,0.00000,0.00000
1002,1003,0,0,3,4361,9000000,2,9000000,0,1,...,1273,197,14.16806,36670,600,2953,257,0,0.00000,0.00000
1003,1004,0,0,0,4108,12000000,0,12000000,0,0,...,665,183,20.80075,7371,369,767,125,0,0.00000,0.00000
1004,1005,0,0,13,222,14250000,2,4500000,0,1,...,273,34,12.75701,0,0,0,0,16,7.20721,1.01587

In [ ]:
df_data.info()
df_data.shape
df_data.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Columns: 255 entries, UNIQUE_NO to ACNT_HSCLP_CTZ_DG_YR1
dtypes: float64(38), int64(214), object(3)
memory usage: 2.0+ MB

UNIQUE_NO                    int64
NH_TARGET                    int64
TOT_HSPZ_DYS                 int64
SM_DSAS_ACNT_YR1             int64
PSG_DYS_CNTR_RIST_ACDDY      int64
                            ...
SAJG_NPCNT_YR1               int64
SAJG_INPCNT_YR1              int64
HSCLP_ACNT_YR1               int64
ACNT_CLPHS_CTZ_DG_YR1      float64
ACNT_HSCLP_CTZ_DG_YR1      float64
Length: 255, dtype: object



*   컬럼확인

In [ ]:
column_names = df_data.columns.tolist()
print(column_names)

['UNIQUE_NO', 'NH_TARGET', 'TOT_HSPZ_DYS', 'SM_DSAS_ACNT_YR1', 'PSG_DYS_CNTR_RIST_ACDDY', 'TOT_ISAMT', 'HSPZ_CNT_YR1', 'BILG_ISAMT', 'SCRT_CNTR_CNT_MT3', 'CNTR_CNT_YR1', 'SEX', 'ACDD_ISAMT', 'PSG_DYS_CTDD_OGTDD', 'ENT_DCD', 'AGE', 'HSP_KDCD', 'FARM_WKNG_DSTR_YN', 'FDS_MGG_CLCD', 'PSG_DYS_PAYRN_OGTDD_ACDT', 'SM_DSAS_ACNT_MT6', 'HSPZ_CNT_YR5', 'ACD_CNT_YR1', 'SM_DSAS_ACNT_YR3', 'DSBRT', 'ACD_CNT_YR5', 'SUM_INP_FE', 'CNTR_CLCT_PATH_CD', 'RVEX_TRT_NTYN', 'SVCE_CARR_PRD', 'RVCY_CD', 'PSG_DYS_CTDD_PAYRN_OGTDD', 'SAJG_ACCNT_CMPR_NPCNT_RT_YR1', 'PRFP_AGE', 'SM_ACD_TYP_ACNT_YR5', 'ACRS_AVSL_PSB_DSAS_YN', 'SM_ACNT_YR5', 'AVG_HSDYS_CMPR_THSDYS_RT', 'MAJ_DSAS_ACD_CNT_YR5', 'CNCR_DIAG_ISAMT', 'INVST_CNT_YR5', 'RLTP_ACD_CNT_YR2', 'ACRS_MAJ_DSAS_YN', 'ACRS_SELF_DIAG_PSB_DSAS_YN', 'TRT_BASC_BNFAM', 'SM_ACNT_YR3', 'ACRS_KPMD_DSAS_YN', 'SM_ACD_SUCNT_YR5', 'PSG_DYS_ACDDY_ACDT', 'CLMN_MTDCD', 'HTZ_DAY_TC', 'RLLS_SCRT_AMT', 'PSG_DYS_FCNTR_RIST_ACDDY', 'BLLP_ACDP_CUST_RLP_CD', 'SCRT_HSPZ_DYS', 'DUTN_HSPZ_DYS', 'SPF_CND_INP_QTTY', 'BASC_BNFAM', 'MCNTR_BASC_BNFAM', 'ETC_PAY_AMT', 'ISAMT_ADD_AMT', 'ISAMT_RDC_AMT', 'MNUL_RDC_AMT', 'BILG_ISAMT_PAY_AMT', 'APPRM', 'NNRCV_PRM', 'PV_RCPRM', 'SCRM_DAM_SCRT_AMT', 'NMNL_DSB_PAYRT', 'PTT_ISAMT_PAY_OBJ_YN', 'EXCL_MMCNT', 'SRVL_BNFAM_PAY_TPCD', 'BILG_ISAMT_CNTR', 'BASC_BNFAM_CNTR', 'MCNTR_BASC_BNFAM_CNTR', 'TRT_BASC_BNFAM_CNTR', 'ETC_PAY_AMT_CNTR', 'ISAMT_ADD_AMT_CNTR', 'ISAMT_RDC_AMT_CNTR', 'MNUL_RDC_AMT_CNTR', 'BILG_ISAMT_PAY_AMT_CNTR', 'APPRM_CNTR', 'NNRCV_PRM_CNTR', 'PV_RCPRM_CNTR', 'PROD_LCCD', 'PROD_MCCD', 'RCVE_SCD', 'PSMG_TPCD', 'CDTL_CNTR_YN', 'ISRD_DFFR_YN', 'CNTR_CHGYN', 'RENW_CNTR_YN', 'RSTYN', 'CI_OCU_YN', 'OPRN_CED_YN', 'PRS_RCVE_DTM_STOP_MMCNT', 'ACM_RCVE_DTM_STOP_MMCNT', 'LS_RVNT', 'ENT_AMT', 'PRM', 'MBP', 'RENW_TRT_YN', 'CNTR_CLP_RLP_CD', 'RSK_GCD', 'PRFP_BLLP_DPR_SM_YM', 'CNTRP_CLP_SLF_YN', 'MCNTR_TRT_PRM_RTO', 'SVTP_PROD_YN', 'OPTT_NBTM', 'OTC_PS_NBTM', 'HSPZ_SUROP_SC', 'DSTR_PTCRT', 'HSEX_STAMT', 'SLF_BDN_STAMT', 'MDTTM_NBTM', 'LONG_DIST_ACDYN', 'LSASL_ACPT_YN', 'INSPR_SLF_ACPT_YN', 'ACD_ACPT_PATH_CD', 'SCRT_CNTR_CNT', 'GDAD_ISAMT', 'SRSNS_DSB_ISAMT', 'PSG_DYS_RCNACDT_ACDT', 'NSURP_DSB_BILG_YN', 'MMP_BAS_TOT_PRM', 'ACDP_CLP_SLF_YN', 'TOT_OPTT_NBTM', 'INSP_KPMD_GCD', 'TWINS_YN', 'ACCNT', 'ACCNT_MT6', 'ACCNT_YR1', 'OTBR_ACCNT_YR3', 'CNTR_CNT', 'CNTR_CNT_MT3', 'CNTR_CNT_MT6', 'VLNTR_SUS_HST_YN', 'ACD_CNT', 'ACD_CNT_YR2', 'DSTR_ACD_CNT_YR1', 'DSTR_ACD_CNT_YR2', 'DSTR_ACD_CNT_YR5', 'SUROP_CNT_YR1', 'SUROP_CNT_YR5', 'HSPZ_DYS_YR1', 'HSPZ_DYS_YR5', 'OPTT_NBTM_YR1', 'OPTT_NBTM_YR5', 'PAY_AMT_YR1', 'PAY_AMT_YR5', 'INVST_CNT_YR1', 'DSTR_INVST_CNT_YR5', 'NPAY_AMT', 'NPAY_CNT_YR1', 'NPAY_AMT_YR1', 'NPAY_CNT_YR5', 'BKBON_DSAS_ACCNT_YR5', 'JONT_DSAS_ACCNT_YR5', 'RLTP_INSP_KPMD_GCD', 'RLTP_CNTR_CNT', 'RLTP_ACD_CNT', 'RLTP_ACD_CNT_YR1', 'RLTP_PAY_AMT_YR1', 'RLTP_INVST_CNT_YR1', 'RLTP_NPAY_CNT_YR1', 'RLTP_NPAY_AMT_YR1', 'RLTP_CCNT_CMPR_ACNT_RT_YR1', 'RLTP_ACNT_CMPR_IVCNT_RT_YR1', 'RLTP_ACNT_CMPR_NPCNT_RT_YR1', 'RLTP_IVCNT_CMPR_NPCNT_RT_YR1', 'RLTP_PYAMT_CMPR_NPYAMT_RT_YR1', 'CNTRP_ACCNT', 'ACCS_AVSL_PSB_DSAS_YN', 'ACCS_SELF_DIAG_PSB_DSAS_YN', 'ACCS_CTDS_YN', 'ACCS_NSBB_DSAS_YN', 'ACCS_MAJ_DSAS_YN', 'ACCS_BKBON_DSAS_YN', 'ACCS_JONT_DSAS_YN', 'ACRS_CTDS_YN', 'ACRS_NSBB_DSAS_YN', 'ACRS_BKBON_DSAS_YN', 'ACRS_JONT_DSAS_YN', 'KPMD_CLP_YN', 'FC_MORTL_YR1', 'FC_CNTR_CNT', 'FC_ACD_CNT_YR1', 'FC_ACD_CNT_YR2', 'FC_PAY_AMT_YR1', 'FC_INVST_CNT_YR1', 'FC_NPAY_CNT_YR1', 'FC_NPAY_AMT_YR1', 'CLP_CNNT_CMPR_ACNT_RT_YR1', 'CLP_ACNT_CMPR_INVST_RT_YR1', 'CLP_ACNT_CMPR_NPCNT_RT_YR1', 'CLP_INVST_CMPR_NPCNT_RT_YR1', 'CLP_PYAMT_CMPR_NPYAMT_RT_YR1', 'DR_ACNT_YR1', 'DR_PYAMT_YR1', 'DR_INVST_CNT_YR1', 'DR_NPAY_CNT_YR1', 'DR_NPAY_AMT_YR1', 'DR_ACNT_CMPR_INVST_RT_YR1', 'DR_ACNT_CMPR_NPCNT_RT_YR1', 'DR_INVST_CMPR_NPCNT_RT_YR1', 'DR_PYAMT_CMPR_NPYAMT_RT_YR1', 'DR_DIAG_ACNT_YR1', 'KPMD_HSP_YN', 'HSP_ACNT_YR1', 'HSP_PYAMT_YR1', 'HSP_INVST_CNT_YR1', 'HSP_NPAY_CNT_YR1', 'HSP_NPAY_AMT_YR1', 'HSP_ACNT_CMPR_INVST_RT_YR1', 'HSP_ACNT_CMPR_NPCNT_RT_YR1', 'HSP_INVST_CMPR_NPCNT_RT_YR1', 'HSP_PYAMT_CMPR_NPYAMT_RT_YR1', 'HSP_LONG_DIST_ACNT_YR1', 'KPMD_JOBGR_YN', 'JOBGR_RSK_GRD_CD', 'SM_ACD_TYP_ACCNT', 'SM_ACD_TYP_NPCNT_YR5', 'SM_DSAS_HSPZ_DYS', 'SM_BLCNT', 'SM_ACNT_MT6', 'SM_ACNT_YR1', 'SM_ACD_NPCNT_YR5', 'SM_ACD_HSCNT_YR5', 'SM_ACD_HSDAY_YR5', 'DSTR_SM_ACD_OCCNT', 'RCN_DSTR_SM_ACCD_ACRD_YN', 'HIRA_AVG_HSPZ_DYS', 'HIRA_AVG_OPTT_DYS', 'AVG_OPDYS_CMPR_TOPNT_RT', 'SAMG_ACCNT_YR1', 'SAMG_IVCNT_YR1', 'SAMG_NPCNT_YR1', 'SAMG_INPCNT_YR1', 'SAMG_ACCNT_CMPR_NPCNT_RT_YR1', 'SADS_ACCNT_YR1', 'SADS_IVCNT_YR1', 'SADS_NPCNT_YR1', 'SADS_INPCNT_YR1', 'SADS_ACCNT_CMPR_NPCNT_RT_YR1', 'SARG_ACCNT_YR1', 'SARG_IVCNT_YR1', 'SARG_NPCNT_YR1', 'SARG_INPCNT_YR1', 'SARG_ACCNT_CMPR_NPCNT_RT_YR1', 'SAJG_ACCNT_YR1', 'SAJG_IVCNT_YR1', 'SAJG_NPCNT_YR1', 'SAJG_INPCNT_YR1', 'HSCLP_ACNT_YR1', 'ACNT_CLPHS_CTZ_DG_YR1', 'ACNT_HSCLP_CTZ_DG_YR1']

### 열별 결측값(missing value) 확인

다음 코드는 `df_data` DataFrame의 각 열에 있는 결측값(NaN:Not a Number)의 개수를 계산합니다. 그런 다음 결측값이 하나라도 있는 열만 필터링하여 표시합니다.

In [ ]:
missing_counts = df_data.isnull().sum()
columns_with_missing_values = missing_counts[missing_counts > 0]
display(columns_with_missing_values)

ENT_DCD                  446
CNTR_CLCT_PATH_CD        313
RVEX_TRT_NTYN            210
PSMG_TPCD                  5
RENW_CNTR_YN             582
RSTYN                    612
CNTR_CLP_RLP_CD          945
LSASL_ACPT_YN              1
INSPR_SLF_ACPT_YN          1
PSG_DYS_RCNACDT_ACDT    1005
INSP_KPMD_GCD            983
RLTP_INSP_KPMD_GCD       980
JOBGR_RSK_GRD_CD         608
dtype: int64

In [ ]:
df_data['CNTR_CLP_RLP_CD']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1000   NaN
1001   NaN
1002   NaN
1003   NaN
1004   NaN
Name: CNTR_CLP_RLP_CD, Length: 1005, dtype: float64